// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXWdlM-LFpimo9L2yUH2rv0bOmmTGfUG8',
    appId: '1:705772480219:web:0fdca5249e090a75060efe',
    messagingSenderId: '705772480219',
    projectId: 'blocparty-team6-cs3541',
    authDomain: 'blocparty-team6-cs3541.firebaseapp.com',
    storageBucket: 'blocparty-team6-cs3541.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe1Wv4AILrRU5Zi46rvvp63mUx72tFB28',
    appId: '1:705772480219:android:a8acb383293b43a2060efe',
    messagingSenderId: '705772480219',
    projectId: 'blocparty-team6-cs3541',
    storageBucket: 'blocparty-team6-cs3541.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtA4NidY7hX4t4cCmurM7vhvH8s8Y4vpA',
    appId: '1:705772480219:ios:6b91fc5730c82ad9060efe',
    messagingSenderId: '705772480219',
    projectId: 'blocparty-team6-cs3541',
    storageBucket: 'blocparty-team6-cs3541.firebasestorage.app',
    iosBundleId: 'com.example.blocparty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtA4NidY7hX4t4cCmurM7vhvH8s8Y4vpA',
    appId: '1:705772480219:ios:6b91fc5730c82ad9060efe',
    messagingSenderId: '705772480219',
    projectId: 'blocparty-team6-cs3541',
    storageBucket: 'blocparty-team6-cs3541.firebasestorage.app',
    iosBundleId: 'com.example.blocparty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXWdlM-LFpimo9L2yUH2rv0bOmmTGfUG8',
    appId: '1:705772480219:web:3c21c61f3eae20b6060efe',
    messagingSenderId: '705772480219',
    projectId: 'blocparty-team6-cs3541',
    authDomain: 'blocparty-team6-cs3541.firebaseapp.com',
    storageBucket: 'blocparty-team6-cs3541.firebasestorage.app',
  );
}
